services:
  mariadb:
    image: "mariadb"
    restart: "on-failure:3"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "products"
    volumes:
      - "./data/mariadb:/var/lib/mysql"

  backend:
    build: "./backend"
    depends_on:
      - "mariadb"
    restart: "on-failure:3"
    environment:
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "${DB_ROOT_PASSWORD}"
      SPRING_DATASOURCE_URL: "jdbc:mariadb://mariadb:3306/products"
    ports:
      - "${BACKEND_EXTERNAL_PORT}:8080"

  phpmyadmin:
    image: "phpmyadmin"
    depends_on:
      - "mariadb"
    restart: "on-failure:3"
    environment:
      PMA_HOST: "mariadb"
    ports:
      - "127.0.0.1:${PHPMYADMIN_EXTERNAL_PORT}:80"

  frontend_dev:
    build: "./front"
    volumes:
      - ./front/src:/app/src  # Mount the local source code to the container
      - ./front/public:/app/public  # Mount the public directory
      - /app/node_modules  # Ensure node_modules is not overwritten by host
    environment:
      - CHOKIDAR_USEPOLLING=true  # Fixes issue with file system changes not detected in some environments
    ports:
      - "${FRONTEND_EXTERNAL_PORT}:3000"
volumes:
  mysql_data:
